#!/usr/bin/env node
/**
 * Pre-build content synchroniser.
 *
 * Copies the asciinema cast files and a few raw text artefacts from the
 * package root (../) into `static/recordings/` and `src/lib/generated/` so
 * the docs site stays in lockstep with the published package without
 * duplicating prose. Runs as `predev` and `prebuild`.
 */
import { mkdirSync, copyFileSync, readFileSync, writeFileSync, existsSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const siteRoot = resolve(here, '..');
const pkgRoot = resolve(siteRoot, '..');

function ensureDir(p) {
  mkdirSync(p, { recursive: true });
}

function copy(rel) {
  const from = resolve(pkgRoot, rel);
  if (!existsSync(from)) {
    console.warn(`[sync-content] missing: ${from}`);
    return;
  }
  const to = resolve(siteRoot, 'static', rel.replace(/^assets\//, ''));
  ensureDir(dirname(to));
  copyFileSync(from, to);
  console.log(`[sync-content] copy ${rel} → ${to.replace(siteRoot + '/', '')}`);
}

function snapshot(rel, outName) {
  const from = resolve(pkgRoot, rel);
  if (!existsSync(from)) {
    console.warn(`[sync-content] missing: ${from}`);
    return;
  }
  const dest = resolve(siteRoot, 'src/lib/generated', outName);
  ensureDir(dirname(dest));
  const raw = readFileSync(from, 'utf8');
  writeFileSync(dest, `// AUTO-GENERATED by scripts/sync-content.mjs from ${rel}.\nexport default ${JSON.stringify(raw)};\n`);
  console.log(`[sync-content] snapshot ${rel} → src/lib/generated/${outName}`);
}

ensureDir(resolve(siteRoot, 'src/lib/generated'));

snapshot('COMPATIBILITY.md', 'compatibility.js');
snapshot('CHANGELOG.md', 'changelog.js');
snapshot('examples/code-review-agent/tools.ts', 'example-tools.js');
snapshot('examples/code-review-agent/illegal-call.demo.ts', 'illegal-call.js');

console.log('[sync-content] done');
